[package]
name = "discombobugraph"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = "0.23.3"
statrs = "0.18.0"

[lib]
name = "discombobugraph"
crate-type = ["cdylib", "lib"]

[[bin]]
name = "discombobugraph"
